### ISSUE TITLE
Add dist file

### ISSUE THREAD

**Issue by baldore** [jaxgeller/tweezer.js#1]
Hi! It should be great if you can add a .min.js file for this repository. I think it doesn't require a lot of effort. Thanks!

**Comment by jaxgeller** [comment]
@baldore I am sorry for the late reply. Unfortunately, I will not be adding a .min.js file for this repository. This library is meant to be used with a modern workflow via npm. I believe ES6 and npm together are the future, and I want to do my best to push those two forward. 

If you're looking for a modern workflow that allows for ES6 and module bundling I suggest taking a look at [outset](https://github.com/callmecavs/outset)

Thank You.

**Comment by baldore** [comment]
@jaxgeller aaaaah ok got it. In that case, I agree :goat:
