### ISSUE TITLE
How would you run two tweens at the same time?

### ISSUE THREAD

**Issue by guidobouman** [jaxgeller/tweezer.js#5]
Animating a single prop is easy-peasy. But how would you approach animating two integers at the same time? Let's say scrollTop & scrollLeft.

I was thinking about putting in an object of integers into Tweezer.js. That would be the easiest option, but requires an update in the module. Or I could (in my own code) tween from 1 to lets say 100, and calculate my own intermediate values. But that feels weird, and would require me to keep state about the initial & target values. What do you say?

**Comment by guidobouman** [comment]
@jaxgeller Ping!

**Comment by jaxgeller** [comment]
I would say this is probably a limitation of tweezer. 

> Animating a single prop is easy-peasy. But how would you approach animating two integers at the same time? Let's say scrollTop & scrollLeft.

This your best bet, but i suppose you could also run two instances.

> Or I could (in my own code) tween from 1 to lets say 100, and calculate my own intermediate values.


Here's an untested example of two instances, but i would opt for the calculation of intermediate values

```es6
button.onclick = ()=> {
  new Tweezer({
    start: window.scrollY,
    end: elementYouWantToScrollTo.getBoundingClientRect().top + window.scrollY
  }).on('tick', v => window.scrollTo(window.scrollX, v)).begin()

  new Tweezer({
    start: window.scrollX,
    end: elementYouWantToScrollTo.getBoundingClientRect().top + window.scrollX
  }).on('tick', v => window.scrollTo(v, window.scrollY)).begin()
}
```

**Comment by jonahbron** [comment]
@jaxgeller Is there any interest in adding (approving a PR with) support for this if it's done in a tree-shakable way?  Seems like the extra code size would be minimal.  A feature like this is especially valuable for an Angular application, where every requestAnimationFrame triggers change detection.  Animating several properties in a single frame could have a measurable impact on app performance.

**Comment by guidobouman** [comment]
@jonahbron For now I've implemented an intermediate value that I use to calculate the progression on the tween.

```js
new Tweezer({
  start: 0,
  end: TWEEN_MAX_VALUE,
}).on('tick', value => {
    const scrollTopDelta = this.targetScrollOffset.top - this.currentScrollOffset.top;
    const scrollTop = this.currentScrollOffset.top + (scrollTopDelta * value / TWEEN_MAX_VALUE);
    this.scrollContainer.scrollTop = scrollTop;

    const scrollLeftDelta = this.targetScrollOffset.left - this.currentScrollOffset.left;
    const scrollLeft = this.currentScrollOffset.left + (scrollLeftDelta * value / TWEEN_MAX_VALUE);
    this.scrollContainer.scrollLeft = scrollLeft;
});
```

See: https://github.com/guidobouman/panelsnap/blob/develop/src/panelsnap.js#L169

Disadvantage: Requires me to keep state about the start & end values. Something Tweezer should actually do if you ask me.

**Comment by jonahbron** [comment]
@guidobouman That looks like a good solution.  But at this point your application is the one doing the tweening, which I would argue is sub-optimal.  And that shows it wouldn't take much additional code to implement this in the library itself.

**Comment by guidobouman** [comment]
@jonahbron Completely agree.

**Comment by jonahbron** [comment]
@guidobouman In case you're still interested, I forked and made a PR (#7) to add this functionality.  If you need it sooner than it's merged, there's an `#installable` branch you can depend on directly.  That's what I'm doing for now.
